# This is a basic workflow to help you get started with Actions

name: CI Docs static pages
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:
    branches: 
      - docs/**
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docfx-action
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docs/docfx.json
    
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
        force_orphan: true